### ISSUE TITLE
webview-ui-toolkit doesn't work in vscode extension

### ISSUE THREAD

**Issue by hlamranialaoui** [microsoft/vscode-webview-ui-toolkit-samples#134]
### Describe the bug

I developed an extension in vscode with the webview-ui-toolkit library, then i package it with vsce package. 
When I generate the .vsix extension and install it in local to test, it doesn't take the correct visual.

### To reproduce

- build successfully
- run:  vsce package
- the extension.vsix generated
- open vscode studio and install new extension with :  install from VSIX...

### Expected behavior
Here is the visual in local, with debug mode. I want to have the same result with the packaging extension.

![image](https://user-images.githubusercontent.com/90907349/216368943-d56f244b-a890-4ae5-bf35-7c989227901e.png)

### Screenshots
The result of the extension installed
![image](https://user-images.githubusercontent.com/90907349/216368784-e120493d-863a-4d35-b4eb-22b316d18333.png)

### Desktop (please complete the following information):
OS Version: Windows 10 Home
Toolkit Version: npm 9.2.0 , node v19.3.0
### Additional context
package.json file

![image](https://user-images.githubusercontent.com/90907349/216372639-1135bbac-2445-4856-80db-1b89e0c0adf2.png)
![image](https://user-images.githubusercontent.com/90907349/216372776-87324e35-30d5-41b5-b8aa-3e16044f759d.png)

**Comment by hawkticehurst** [comment]
Thanks for the report @hlamranialaoui 

Based on the images it looks like the components are not being registered correctly once the extension has been packaged, which from previous experience usually means there's something going wrong with how the code is being built/compiled

Could you share screenshots of both:

1. Your webpack config
2. Any errors that are showing up in the inspector while running your extension*

*To do this: 
- Open the VSIX-based extension 
- Run the "Developer: OpenWebview Developer Tools" command
- Look at the "Console" tab
- Take a screenshot of any errors/warnings

**Comment by hlamranialaoui** [comment]
Thank you for your answer @hawkticehurst

Here are webpack.config file and debug console tab in local
![image](https://user-images.githubusercontent.com/90907349/216564085-89a99da6-0ed3-41e6-8f3e-53273d2034d4.png)
![image](https://user-images.githubusercontent.com/90907349/216566310-1cc99208-d94b-4f24-ace8-9521821582e8.png)

Here is the console tab from "Developer: OpenWebview Developer Tools"
![image](https://user-images.githubusercontent.com/90907349/216567797-55b6baa7-5e34-475f-8b12-c0f37308c6c6.png)

**Comment by hawkticehurst** [comment]
Of course, thanks for the screenshots!

So yeah based on the last screenshot there's definitely something going on with correctly loading the toolkit source code –– notably the error stating:

```
Error: Unable to read file 'c:\Users\ ... \dist\toolkit.js' (Error: Unable to resolve non-existent file...)
```

This is definitely causing the error you're seeing where the toolkit components are not loading (the toolkit code doesn't exist!). It also looks like (based on the file paths listed in the errors) you're seemingly using the older method of importing the toolkit code by directly referencing the bundled `toolkit.js` file inside of `node_modules`.

With that in mind what does you're `.vscodeignore` file look like? This is a file that (like .gitignore or .npmignore) will ensure any files/glob paths listed **_do not_** get included in the final production build of your extension. Oftentimes `node_modules/` is listed in this file and so I'd wager this is what is causing the `toolkit.js` (and `codicon.css` for that matter) to not show up in your VSIX version of the extension.

The solution would be to explicitly allow the `toolkit.js` (and `codicon.css`) files using the `!` syntax (which will unignore files):

```
# All of node modules will still be ignored
node_modules/

# The toolkit and codicon files will be explicitly allowed
!node_modules/@vscode/webview-ui-toolkit/dist/toolkit.js
!node_modules/@vscode/codicons/dist/codicon.css
```

**I wouldn't actually do this however!**

With all that said, I would actually discourage this method of importing/using the toolkit since it is quite brittle.

Instead I'll point you towards a new getting started guide and associated sample extensions that I published a few weeks ago.

They demonstrate how to configure the toolkit using our import and registration API and use esbuild to bundle the code. I also create a sample extension that covers the same ideas discussed in the getting started guide but uses webpack to bundle code instead (if you prefer that).

- [Getting started guide](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/docs/getting-started.md)
- [Hello world sample (esbuild)](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/hello-world)
- [Hello world sample (webpack)](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/hello-world-webpack)

Finally, the [`components-gallery`](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/component-gallery) sample extension demonstrates how to use codicons in your extension if you snoop look across a few of the source code and config files.

--

_P.S. I'm also about to be out of office for the couple of weeks starting after today, so if you respond with any updates I will circle back once I've returned. Hope this all helps and best of luck!_

**Comment by hlamranialaoui** [comment]
Hello, thank you, it's working !!
I just add  thoses lines to my config in .vscodeignore.
Best regards.

**Comment by hawkticehurst** [comment]
Thrilled to hear it! You're welcome :)

Going to go ahead and close this issue now too. If you have any more issues/questions feel free to reopen this issue or create a new one
