### ISSUE TITLE
monorepo: load toolkit.js results in 404

### ISSUE THREAD

**Issue by atanasster** [microsoft/vscode-webview-ui-toolkit-samples#36]
### Describe the bug

When trying to load `toolkit.js` as described in the examples results in a 404 error from VSCode server.

### To reproduce

Using the following code
```
 const toolkitUri = getUri(webview, extensionUri, [
      '..',
      '..',
      'node_modules',
      '@vscode',
      'webview-ui-toolkit',
      'dist',
      'toolkit.js',
    ]);
```
here https://github.com/ccontrols/structured-types/blob/44e4ff0bfc3d06a138c39bd47b635627bffd17ea/packages/vscode-plugin/src/ContentProvider.ts#L122

### Expected behavior

Copying `toolkit.js` to the `dist` folder of the extension works 

### Screenshots

![grab189](https://user-images.githubusercontent.com/6075606/138781403-7e0add6f-9d8a-4272-ad24-91aecc96b971.jpg)

**Comment by RandomFractals** [comment]
I ran into the same issue in my new Tabular Data viewer extension that uses this webview UI toolkit JS for the table view toolbar controls. I am using webpack to bundle it tho: https://github.com/RandomFractals/tabular-data-viewer/issues/44

**Comment by atanasster** [comment]
@RandomFractals i ended up just bundling the toolkit library into the webview bundle itself.

**Comment by hawkticehurst** [comment]
Coming back to this with a fresh mind, I'm realizing this is almost definitely a limitation of the VS Code API itself. 

To verify, could one or both of you do a quick sanity check for me (since I don't have a monorepo at the ready) and see if using the VS Code API directly has the same results (i.e. temporarily replace usages of `getUri` with the API call inside it)?

If you do get the same results I have a suspicion (after looking through some of the VS Code source code) this issue is caused by how the `Uri.joinPath` method normalizes a given path––with the greater point being this is an issue that should be opened in the [vscode repo](https://github.com/microsoft/vscode) itself.

**Comment by hawkticehurst** [comment]
Checking back again––any thoughts @atanasster/@RandomFractals? Would love to be able to verify if this issue should be moved into the VS Code repo.

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) earlier this week on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
